#!/usr/bin/bash

printf "Enter Name with and Version of Linux : "

read linux_name

kodachilinux=`echo $linux_name | egrep 'kodachi|Kodachi' `
alpinelinux=`echo $linux_name | egrep 'alpine|Alpine'`
antixlinux=`echo $linux_name | egrep 'antix|Antix|antiX'`
cyborglinux=`echo $linux_name | egrep 'cyborg|Cyborg|cyborg-hawk|Cyborg-hawk|Cyborg-Hawk|cyborghawk|CyborgHawk'`
litelinux=`echo $linux_name | egrep 'lite|Lite|linux_lite|Linux_Lite'`
slaxlinux=`echo $linux_name | egrep 'slax|Slax|SLAX'` #https://www.slax.org/
grmllinux=`echo $linux_name | egrep 'grml|Grml|GRML'` #https://grml.org/

minimalRockylinux=`echo $linux_name | egrep 'Rocky|rocky|ROCKY|Minimal|minimal'`
Rockylinux=`echo $linux_name | egrep 'Rocky|rocky'`

ubuntulinux=`echo $linux_name | egrep 'Ubuntu|ubuntu'`
manjarolinux=`echo $linux_name | egrep 'manjaro|manjaro'`
deepinlinux=`echo $linux_name | egrep 'deepin|Deepin'`
bodhilinux=`echo $linux_name | egrep 'Bodhi|bodhi'`
openSUSElinux=`echo $linux_name | egrep 'opensuse|Opensuse|openSuse|OPENsuse|openSUSE|OpenSuse'`
Discreetelinux=`echo $linux_name | egrep 'Discreete|discreete'`
lubuntulinux=`echo $linux_name | egrep 'Lubuntu|lubuntu'`
lithiumlinux=`echo $linux_name | egrep 'bunsenlabs|Bunsenlabs|lithium|Lithium'`
Peppermintlinux=`echo $linux_name | egrep 'Peppermint|peppermint'`


printf "Enter SHA256sum : "

read linux_sha


if [ "$kodachilinux" == "kodachi" ] || [ "$kodachilinux" == "Kodachi" ];then
       	if [ "$linux_sha" == 0924920d68c5bdb5edb28bde2730d3831db2da3f5b813a5ad903f10df32fc1cd ];then
       		echo "=> Kodachi Linux : kodachi-8.17-64.iso"
	fi
fi

if [ "$alpinelinux" == "alpine" ] || [ "$alpinelinux" == "Alpine" ];then
	if [ "$linux_sha" == 730aceadaeab93d8bd18ace1575dcbdc5130b211c7e4b50aea7369e5f374a8a9 ];then
       		echo "=> Alpine Linux : alpine-xen-3.13.5-x86_64.iso"

	fi	
fi

if [ "$antixlinux" == "antix" ] || [ "$antixlinux" == "Antix" ] || [ "$antixlinux" == "AntiX" ];then
	if [ "$linux_sha" == 8335d67b52f06673740663aeca108f8ce7990e63ba22750e9454ccc65a0d4ee5 ];then
		echo "=> antiX Linux : antiX-21_x64-full.iso"
	fi	
fi


if [ "$cyborglinux" == "cyborg" ] || [ "$cyborglinux" == "Cyborg" ] ||
	[ "$cyborglinux" == "CyborgHawk" ] || [ "$cyborglinux" == "cyborghawk"] || [ "$cyborglinux" == "cyborg-hawk" ] || [ "Cyborg-Hawk" ];then
	if [ "$linux_sha" == 8335d67b52f06673740663aeca108f8ce7990e63ba22750e9454ccc65a0d4ee5 ];then
		echo "=> Cyborg-Hwak : cyborg-hawk-linux-v-1.1_2.iso"
	fi	
fi


if [ "$litelinux" == "Linux_Lite" ] || [ "$litrelinux" == "linux_lite" ] || [ "$litelinux" == "Lite" ] || [ "$litelinux" == "lite" ];then
	if [ "$linux_sha" == abd13a1aafc5824b68ea3b1e007e85ce39b2e3904f62f4de78f98d7cb5cd4104 ];then
		echo "=> Linux Lite : linux-lite-5.2-64bit.iso"
	fi	
fi

if [ "$litelinux" == "SLAX" ] || [ "$litrelinux" == "Slax" ] || [ "$litelinux" == "slax" ];then
	if [ "$linux_sha" == c3b7fe14f2d5128e6e1a40911956c992e1765364bd2ad74e36a4331150d9bb70 ];then
		echo "=> Slax Linux : slax-64bit-11.4.0.iso"
	fi	
fi

if [ "$litelinux" == "grml" ] || [ "$litrelinux" == "Grml" ] || [ "$litelinux" == "GRML" ];then
	if [ "$linux_sha" == 7cec5cb3816edd55164d8d1cdfc315ecdda1ea26e5daa52fc8462f8d5bdd888d ];then
		echo "=> grml Linux : gml64-full_2021.07.iso"
	fi	
fi

